name: Build

on:
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
      - '**/tsconfig*.json'
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup-node-pnpm

      - name: Cache Turborepo
        uses: ./.github/actions/cache-turbo

      - name: Fetch base commit
        if: github.event_name == 'pull_request'
        run: |
          BASE_SHA='${{ github.event.pull_request.base.sha }}'
          git fetch --no-tags --depth=1 origin ${BASE_SHA}:${BASE_SHA}

      - name: Build (affected only)
        if: github.ref != 'refs/heads/main'
        run: pnpm turbo run build --filter=...['${{ github.event.pull_request.base.sha }}']

      - name: Build (full graph on main)
        if: github.ref == 'refs/heads/main'
        run: pnpm build
