name: Lint and Format

on:
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'eslint.config.mjs'
      - 'pnpm-lock.yaml'
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'eslint.config.mjs'
      - 'pnpm-lock.yaml'

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          cache-dependency-path: pnpm-lock.yaml
          run-install: 'true'
          offline: 'true'

      - name: Cache Turborepo
        uses: ./.github/actions/cache-turbo

      - name: ESLint (affected only)
        run: pnpm lint

      - name: Prettier (check)
        run: pnpm prettier --check .
