name: Run tests and upload coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
  push:
    branches:
      - main # only after merge to main
      # - 'release/**' # (optional) release branches
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'turbo.json'

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # Run on PRs OR on pushes to main/tags (never on feature-branch pushes)
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          cache-dependency-path: pnpm-lock.yaml
          run-install: 'true'
          offline: 'true'

      - name: Cache Turborepo
        uses: ./.github/actions/cache-turbo

      - name: Run tests (Vitest) with coverage in all workspaces
        run: pnpm test:coverage

      - name: Upload results to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '**/coverage/lcov.info'
          flags: unit-tests
          fail_ci_if_error: true
          verbose: true
