name: Typecheck

on:
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'packages/typescript-config/**'
      - 'tsconfig*.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'packages/typescript-config/**'
      - 'tsconfig*.json'
      - 'pnpm-lock.yaml'
      - 'turbo.json'

permissions:
  contents: read

concurrency:
  group: typecheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup-node-pnpm

      - name: Cache Turborepo
        uses: ./.github/actions/cache-turbo

      # Fetch only the PR base commit so Turbo can resolve the filter target
      - name: Fetch base commit
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.base.sha }}:${{ github.event.pull_request.base.sha }}

      # Affected-only on PRs; full graph on main
      - name: Typecheck (affected only)
        if: github.ref != 'refs/heads/main'
        run: pnpm turbo run typecheck --filter=...['${{ github.event.pull_request.base.sha }}']

      - name: Typecheck (full graph on main)
        if: github.ref == 'refs/heads/main'
        run: pnpm turbo run typecheck
